"""
chart_renderer — backend PNG image generation for TradingSpy agent tools.

Mirrors the frontend "Insight by TradingSpy" footer: every chart is stamped with
a TradingSpy attribution footer so generated images are clearly branded, the same
way the web UI watermarks exported charts.

Runs headless with matplotlib's Agg backend (no display required on the server).
"""

import io
import logging

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import yfinance as yf

logger = logging.getLogger(__name__)

FOOTER_TEXT = "Generated by TradingSpy  ·  github.com/mrhustlex/TradingSpy-TradingAgentService"

TS_BG = "#0b1220"
TS_PANEL = "#0f172a"
TS_GRID = "#1e293b"
TS_TEXT = "#e2e8f0"
TS_MUTED = "#94a3b8"
TS_ACCENT = "#22d3ee"


def _fetch_frame(symbol: str, interval: str, period: str) -> pd.DataFrame:
    """Pull OHLCV from yfinance and normalise to a 'Date' column + RangeIndex."""
    symbol = str(symbol).strip().upper().replace("$", "")
    df = (
        yf.Ticker(symbol)
        .history(period=period, interval=interval, auto_adjust=False)
        .dropna(subset=["Close"])
    )
    if df.empty:
        raise ValueError(f"No data for {symbol} ({interval}/{period})")
    df = df.reset_index()
    if "Date" not in df.columns and "Datetime" in df.columns:
        df = df.rename(columns={"Datetime": "Date"})
    df["Date"] = pd.to_datetime(df["Date"])
    return df[["Date", "Open", "High", "Low", "Close", "Volume"]].reset_index(drop=True)


def _style(fig, ax, title: str):
    fig.patch.set_facecolor(TS_BG)
    ax.set_facecolor(TS_PANEL)
    ax.set_title(title, color=TS_TEXT, fontsize=11, fontweight="bold")
    ax.grid(True, color=TS_GRID, linewidth=0.5)
    for spine in ax.spines.values():
        spine.set_color(TS_GRID)
    ax.tick_params(colors=TS_MUTED, labelsize=8)
    ax.set_xlabel("")


def _finalize(fig) -> bytes:
    fig.text(0.5, 0.012, FOOTER_TEXT, ha="center", va="center", fontsize=8, color=TS_MUTED)
    buf = io.BytesIO()
    fig.savefig(buf, format="png", bbox_inches="tight", facecolor=TS_BG, dpi=110)
    plt.close(fig)
    return buf.getvalue()


def _error_png(message: str) -> bytes:
    fig, ax = plt.subplots(figsize=(8, 2))
    ax.set_facecolor(TS_PANEL)
    fig.patch.set_facecolor(TS_BG)
    ax.text(0.02, 0.5, message, color=TS_TEXT, fontsize=9, va="center", wrap=True)
    ax.axis("off")
    return _finalize(fig)


def _draw_candles(ax, df: pd.DataFrame):
    x = np.arange(len(df))
    width = 0.6
    for i, row in df.iterrows():
        color = "#26a69a" if row["Close"] >= row["Open"] else "#ef5350"
        ax.plot([i, i], [row["Low"], row["High"]], color=color, linewidth=0.8, zorder=1)
        bottom = min(row["Open"], row["Close"])
        height = abs(row["Close"] - row["Open"]) or 0.0001
        ax.add_patch(plt.Rectangle((i - width / 2, bottom), width, height, color=color, zorder=2))
    ax.set_xlim(-1, len(df))
    # a handful of date ticks
    if len(df) > 1:
        step = max(1, len(df) // 6)
        ticks = list(range(0, len(df), step))
        ax.set_xticks(ticks)
        ax.set_xticklabels([df["Date"].iloc[t].strftime("%Y-%m-%d") for t in ticks], rotation=30, ha="right")


def _candles_png(symbol: str, interval: str, period: str) -> bytes:
    df = _fetch_frame(symbol, interval, period)
    fig, ax = plt.subplots(figsize=(10, 5))
    _draw_candles(ax, df)
    _style(fig, ax, f"{symbol} candles ({interval} · {period})")
    return _finalize(fig)


def _expected_pattern_png(symbol: str, interval: str, horizon: int, lookback: int) -> bytes:
    from expected_pattern import generate_expected_pattern

    res = generate_expected_pattern.invoke(
        {"ticker": symbol, "interval": interval, "horizon": horizon, "lookback": lookback}
    )
    if "error" in res:
        return _error_png(f"{symbol} expected pattern: {res['error']}")

    history = res.get("history") or []
    forecast = res.get("forecast") or []
    if not history or not forecast:
        return _error_png(f"{symbol}: empty expected-pattern result")

    n_hist = len(history)
    x_hist = np.arange(n_hist)
    close_hist = [h["close"] for h in history]
    x_fc = np.arange(n_hist - 1, n_hist - 1 + len(forecast))
    exp = [f["expected_close"] for f in forecast]
    lo = [f["lower_80"] for f in forecast]
    hi = [f["upper_80"] for f in forecast]

    fig, ax = plt.subplots(figsize=(10, 5))
    ax.plot(x_hist, close_hist, color=TS_ACCENT, linewidth=1.4, label="History close")
    ax.plot(x_fc, exp, color="#a78bfa", linewidth=1.4, label=f"Median ({res.get('direction')})")
    ax.fill_between(x_fc, lo, hi, color="#a78bfa", alpha=0.18, label="80% band")
    ax.axvline(n_hist - 1, color=TS_MUTED, linestyle="--", linewidth=0.8)
    _style(fig, ax, f"{symbol} expected pattern — {res.get('direction')} ({res.get('expected_end_return_pct')}%)")
    ax.legend(loc="upper left", fontsize=8, facecolor=TS_PANEL, labelcolor=TS_TEXT)
    return _finalize(fig)


def _pattern_detection_png(symbol: str, interval: str, period: str, patterns) -> bytes:
    from pattern_detector import detect_all

    df = _fetch_frame(symbol, interval, period)
    frame = df[["Date", "Open", "High", "Low", "Close", "Volume"]].reset_index(drop=True)
    results = detect_all(frame, patterns)

    fig, ax = plt.subplots(figsize=(10, 5))
    _draw_candles(ax, frame)
    for r in results:
        if not r.get("detected"):
            continue
        for m in (r.get("detail") or {}).get("markers", []):
            idx = m.get("index")
            if isinstance(idx, (int, np.integer)) and 0 <= int(idx) < len(frame):
                price = (
                    frame["Low"].iloc[int(idx)]
                    if m.get("position") == "belowBar"
                    else frame["High"].iloc[int(idx)]
                )
                ax.scatter(int(idx), price, color=m.get("color", "#f59e0b"), s=42, zorder=3, edgecolors="white", linewidths=0.4)

    detected = [f"{r['pattern']}({r.get('score')})" for r in results if r.get("detected")]
    title = f"{symbol} pattern detection — " + (", ".join(detected) if detected else "no patterns detected")
    _style(fig, ax, title)
    return _finalize(fig)


def render_png(
    symbol: str,
    kind: str,
    interval: str = "1d",
    period: str = "6mo",
    horizon: int = 20,
    lookback: int = 180,
    patterns=None,
) -> bytes:
    """Single entry point used by the render_chart_image agent tool."""
    kind = str(kind).lower()
    if kind == "candles":
        return _candles_png(symbol, interval, period)
    if kind == "expected_pattern":
        return _expected_pattern_png(symbol, interval, horizon, lookback)
    if kind == "pattern_detection":
        return _pattern_detection_png(symbol, interval, period, patterns)
    raise ValueError("kind must be one of candles, expected_pattern, pattern_detection")
